name: Run Tests on Long and Anh branches

on:
  push:
    branches:
      - long
      - anh

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies 
        run: npm ci
        working-directory: ./server

      - name: Run linter tests 
        run: npm test
        working-directory: ./server